FROM ubuntu:22.04
ENV SYS_UTILS="git git-lfs python3 python3-dev python-is-python3 tmux curl vim nano openssh-server rsync"

RUN apt update && apt upgrade -y && apt install -y ${SYS_UTILS} 

# Add starfive user
RUN useradd -d /home/starfive -s /bin/bash -m starfive && echo 'starfive:starfive' | chpasswd

# Expose ssh port
EXPOSE 22

# Provide entrypoint to start ssh server automatically
ENTRYPOINT service ssh restart && bash